# Generated by Django 3.1.7 on 2021-03-20 15:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=255, verbose_name='bank name')),
                ('contact_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('branches', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('loan_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.CharField(max_length=10)),
                ('loan_name', models.CharField(max_length=255, verbose_name='loan name')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='interest rate')),
                ('min_term', models.IntegerField(verbose_name='minimum term')),
                ('max_term', models.IntegerField(verbose_name='maximum term')),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='minimum loan amount')),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='maximum loan amount')),
                ('min_annual_income', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='minimum annual income')),
                ('min_age', models.IntegerField(verbose_name='minimum age')),
                ('max_age', models.IntegerField(verbose_name='maximum age')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loantype')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
    ]
